apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-nginx
  namespace: default
  labels:
    app: learn-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learn-nginx
  template:
    metadata:
      labels:
        app: learn-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
